when@dev: &dev
    # See full configuration: https://symfony.com/bundles/ZenstruckFoundryBundle/current/index.html#full-default-bundle-configuration
    zenstruck_foundry:
        persistence:
            # Flush only once per call of `PersistentObjectFactory::create()`
            flush_once: true

    services:
        _defaults:
            autowire: true
            autoconfigure: true

        App\Tests\Auth\Factory\:
            resource: '%kernel.project_dir%/tests/Auth/Factory/'

        App\Tests\Contact\Factory\:
            resource: '%kernel.project_dir%/tests/Contact/Factory/'

        App\Tests\Newsletter\Factory\:
            resource: '%kernel.project_dir%/tests/Newsletter/Factory/'

        App\Tests\PropertyEstimation\Factory\:
            resource: '%kernel.project_dir%/tests/PropertyEstimation/Factory/'

        App\Tests\DataFixtures\:
            resource: '%kernel.project_dir%/tests/DataFixtures/'

        App\Tests\Story\:
            resource: '%kernel.project_dir%/tests/Story/'

when@test: *dev
