<?php

declare(strict_types=1);

namespace App\Admin\Entity;

use App\Admin\Domain\DocumentCategory;
use App\Admin\Repository\DocumentRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: DocumentRepository::class)]
#[ORM\Table(name: 'document')]
#[UniqueEntity(fields: ['slug'], message: 'admin.tools.documents.form.slug.unique')]
class Document
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    /**
     * Auto-generated by DocumentSlugger from nameFr at persist time —
     * never user-entered, so no #[Assert] constraints (uniqueness is
     * still enforced via the unique column + UniqueEntity above).
     */
    #[ORM\Column(length: 150, unique: true)]
    private ?string $slug = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: 'admin.tools.documents.form.nameFr.notBlank')]
    #[Assert\Length(min: 2, max: 255, minMessage: 'admin.tools.documents.form.nameFr.length', maxMessage: 'admin.tools.documents.form.nameFr.length')]
    private ?string $nameFr = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: 'admin.tools.documents.form.nameEn.notBlank')]
    #[Assert\Length(min: 2, max: 255, minMessage: 'admin.tools.documents.form.nameEn.length', maxMessage: 'admin.tools.documents.form.nameEn.length')]
    private ?string $nameEn = null;

    #[ORM\Column(type: 'text', nullable: true)]
    #[Assert\Length(max: 5000, maxMessage: 'admin.tools.documents.form.description.length')]
    private ?string $descriptionFr = null;

    #[ORM\Column(type: 'text', nullable: true)]
    #[Assert\Length(max: 5000, maxMessage: 'admin.tools.documents.form.description.length')]
    private ?string $descriptionEn = null;

    #[ORM\Column(length: 30, enumType: DocumentCategory::class)]
    #[Assert\NotNull(message: 'admin.tools.documents.form.category.notNull')]
    private ?DocumentCategory $category = null;

    /**
     * Pinned documents are surfaced at the top of the catalogue listing.
     * Used by the admin to keep "high-priority" pieces (e.g. ID card,
     * proof of income) immediately reachable without scrolling.
     */
    #[ORM\Column]
    private bool $pinned = false;

    #[ORM\Column]
    private ?\DateTimeImmutable $createdAt = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): static
    {
        $this->slug = $slug;

        return $this;
    }

    public function getNameFr(): ?string
    {
        return $this->nameFr;
    }

    public function setNameFr(string $nameFr): static
    {
        $this->nameFr = $nameFr;

        return $this;
    }

    public function getNameEn(): ?string
    {
        return $this->nameEn;
    }

    public function setNameEn(string $nameEn): static
    {
        $this->nameEn = $nameEn;

        return $this;
    }

    public function getDescriptionFr(): ?string
    {
        return $this->descriptionFr;
    }

    public function setDescriptionFr(?string $descriptionFr): static
    {
        $this->descriptionFr = $descriptionFr;

        return $this;
    }

    public function getDescriptionEn(): ?string
    {
        return $this->descriptionEn;
    }

    public function setDescriptionEn(?string $descriptionEn): static
    {
        $this->descriptionEn = $descriptionEn;

        return $this;
    }

    public function getCategory(): ?DocumentCategory
    {
        return $this->category;
    }

    public function setCategory(?DocumentCategory $category): static
    {
        $this->category = $category;

        return $this;
    }

    public function isPinned(): bool
    {
        return $this->pinned;
    }

    public function setPinned(bool $pinned): static
    {
        $this->pinned = $pinned;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): static
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    /**
     * Returns the localized name for the given locale, falling back to French.
     * Used by templates / DTOs so the controller never needs locale switches.
     */
    public function getName(string $locale): string
    {
        return 'en' === $locale && null !== $this->nameEn && '' !== $this->nameEn
            ? $this->nameEn
            : (string) $this->nameFr;
    }

    /**
     * Returns the localized description for the given locale, falling back to French.
     */
    public function getDescription(string $locale): ?string
    {
        if ('en' === $locale && null !== $this->descriptionEn && '' !== $this->descriptionEn) {
            return $this->descriptionEn;
        }

        return $this->descriptionFr;
    }
}
