<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Visit client note: the message sent to the client after the visit,
 * written by hand or generated by the AI from the property data and the
 * agent's internal feedback.
 */
final class Version20260818170000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add visit.client_note';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('ALTER TABLE visit ADD client_note LONGTEXT DEFAULT NULL');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE visit DROP client_note');
    }
}
